language: node_js
os:
 - linux
node_js:
  - "11"
  - "10"
  - "8"
  - "6"
  - "4"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'npm install'
  - 'if [ -n "${APHRODITE-}" ]; then npm install "aphrodite@${APHRODITE}" ; fi'
  - 'npm ls >/dev/null'
script:
  - 'if [ -n "${PRETEST-}" ]; then npm run pretest ; fi'
  - 'if [ -n "${POSTTEST-}" ]; then npm run posttest ; fi'
  - 'if [ -n "${COVERAGE-}" ]; then npm run coverage ; fi'
  - 'if [ -n "${APHRODITE-}" ]; then npm run tests-only ; fi'
sudo: false
env:
  - APHRODITE=2
  - APHRODITE=1
  - APHRODITE=0.4
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PRETEST=true
    - node_js: "4"
      env: COVERAGE=true
  allow_failures:
    - os: osx
